version: '3.9'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    ports:
      - 8080:8080
    networks:
      - backend_network
    expose:
      - 8080

  frontend:
    build:
      context: ./frontend/public
      dockerfile: Dockerfile
    restart: always
    container_name: frontend
    ports:
      - 3000:80
    networks:
      - backend_network
    expose:
      - 3000
      - 80
    depends_on:
      - backend

networks:
  backend_network: