version: 2.1

executors:
  windows:
    machine:
      image: windows-server-2019-vs2019:stable

jobs:
  build:
    executor: windows
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            Start-Service docker
      - run:
          name: Build Docker Image
          command: |
            cd backend
            docker build -t gofundease-backend .

  deploy:
    executor: windows
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy Application
          command: |
            echo "Deploying application..."
            # Add your deployment script or commands here

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
