version: 2.1

executors:
  windows:
    machine:
      image: windows-server-2019-vs2019:stable

jobs:
  build:
    executor: windows
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            curl -o nodejs.msi https://nodejs.org/dist/v14.17.0/node-v14.17.0-x64.msi
            Start-Process msiexec.exe -ArgumentList '/i nodejs.msi /quiet /norestart' -Wait
            node --version
            npm --version
      - run:
          name: Install Backend Dependencies
          command: |
            cd backend
            npm install
      - run:
          name: Run Backend Tests
          command: |
            cd backend
            npm test
      - run:
          name: Build Frontend
          command: |
            echo "Building frontend..."
            # Add any frontend build steps here if needed

  deploy:
    executor: windows
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy Application
          command: |
            echo "Deploying application..."
            # Add your deployment script or commands here

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
